ESG/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired

class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    file = StringField('File', validators=[DataRequired()])
    submit = SubmitField('Post')

ESG/main/routes.py
from flask import render_template, request, Blueprint
from ESG.models import Post

main = Blueprint('main', __name__)

@main.route("/")
@main.route("/home")
def home():
  page = request.args.get('page', 1, type=int)
  posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
  return render_template('home.html', posts=posts)

@main.route("/about")
def about():
  return render_template('about.html', title='About')

ESG/posts/routes.py
import os
from flask import (render_template, url_for, flash, redirect, request, abort, Blueprint, current_app)
from flask_login import current_user, login_required
from werkzeug.utils import secure_filename
from ESG import db
from ESG.models import Post
from ESG.posts.forms import PostForm
# from flask import current_app

posts = Blueprint('posts', __name__)

@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
  form = PostForm()
  if form.validate_on_submit():
    post = Post(title=form.title.data, content=form.content.data, file=form.file.data, author=current_user)
    db.session.add(post)
    db.session.commit()
    flash('Your post has been created!', 'success')
    return redirect(url_for('main.home'))
  return render_template('create_post.html', title='New Post', form=form, legend='New Post')

@posts.route("/post/upload", methods=['GET', 'POST'])
@login_required
def upload():        
  form = PostForm()
  if request.method == 'POST' and 'file' in request.files:
    f = request.files['file']
    filename = secure_filename(f.filename)
    f.save(os.path.join(current_app.config['MEDIA'], filename))                
    fname = f.filename
    form.file.data = current_app.config['MEDIA'] 
    
    return redirect(url_for('posts.new'))
    # return render_template('create_post.html', title='New Post',
    #                    form=form, legend='New Post')

  # message = '파일 업로드에 실패하였습니다'    
  # return render_template('upload.html', message=message)
  # return render_template('create_post.html', title='New Post',
  #                        form=form, legend='New Post')    

@posts.route("/post/<int:post_id>")
def post(post_id):
  post = Post.query.get_or_404(post_id)
  return render_template('post.html', title=post.title, post=post)

@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
  post = Post.query.get_or_404(post_id)
  if post.author != current_user:
    abort(403)
  form = PostForm()
  if form.validate_on_submit():
    post.title = form.title.data
    post.content = form.content.data
    db.session.commit()
    flash('Your post has been updated!', 'success')
    return redirect(url_for('posts.post', post_id=post.id))
  elif request.method == 'GET':
    form.title.data = post.title
    form.content.data = post.content
  return render_template('create_post.html', title='Update Post', form=form, legend='Update Post')

@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
  post = Post.query.get_or_404(post_id)
  if post.author != current_user:
    abort(403)
  db.session.delete(post)
  db.session.commit()
  flash('Your post has been deleted!', 'success')
  return redirect(url_for('main.home'))

ESG/qpra/routes.py
from flask import render_template, request, Blueprint, url_for, flash, redirect
# import copy
from ESG import db
from ESG.models import Model, Category, Distribution
from ESG.qpra.forms import ModelForm, SimForm, DIST
from ESG.qpra.query import sqModelUser,sqDelModel,sqModelID
from ESG.qpra.distributions import DTPerti,DTTriangPerc,DTLognormal,DTNormal,DTIntuniform,DTUniform,DTGamma,DTExponential,DTBinomial,DTPoisson,DTBernoulli,DTPertPerc,DTTriangPerc,DTTriangular
qpra = Blueprint('qpra', __name__)

@qpra.route("/qpra", methods = ['POST', 'GET'])
def home():    
  user_id = 0
  sql = sqModelUser.format(user_id)  
  models= db.session.execute(sql)
  # varValues = copy.deepcopy(models)
  # [var for var in models]
  varValues = []
  for varValue in models:
    fprob = 0.0; sprob = 0.0
    fabbr = varValue[10];param10 = varValue[4];param20 = varValue[5]
    sabbr = varValue[11];param11 = varValue[7];param21 = varValue[8];param31 = varValue[9]
    # print('0modelname:',varValue[1],'fabbr:',fabbr,'sabbr:',sabbr)
    if fabbr=='BIN':
      fprob = DTBinomial(param10,param20)
    elif fabbr=='POI':
      fprob = DTPoisson(param10)
    elif fabbr=='BER':
      fprob = DTBernoulli(param10)
    elif fabbr=='INT':
      fprob = DTIntuniform(param10,param20)  
    
    if sabbr=='UNI':
      sprob = DTUniform(param11,param21)
    elif sabbr=='TRI':
      sprob = DTTriangular(param11,param21,param31)  
    elif sabbr=='TRP':
      sprob = DTTriangPerc(param11,param21,param31)        
    elif sabbr=='PER':  
      sprob = DTPerti(param11,param21,param31)  
    elif sabbr=='GAM':
      sprob = DTGamma(param11,param21)
    elif sabbr=='PEP':
      sprob = DTPertPerc(param11,param21,param31)  
    elif sabbr=='LOG':
      sprob = DTLognormal(param11,param21)  
    elif sabbr=='NOR':
      sprob = DTNormal(param11,param21)  
    elif sabbr=='EXP':
      sprob = DTExponential(param11)    

    dic = {'id':varValue[0],'modelname':varValue[1],'category':varValue[2],'fdist':varValue[3],'param10':param10,'param20':param20, \
      'sdist':varValue[6],'param11':param11,'param21':param21,'param31':param31,'fabbr':fabbr,'sabbr':sabbr,'fprob':fprob,'sprob':sprob }
    print('1modelname:',varValue[1],'fabbr:',fabbr,'sabbr:',sabbr,'fprob:',fprob,'sprob:',sprob)
    # print(dic,'\n')    
    varValues.append(dic)
  
  mform = ModelForm()# user id를 매개변수로 전달하여 쿼리하여 모델과 시뮬레이션 정보 장전
  sform = SimForm()
  return render_template('qpra.html',models=varValues,modelform=mform,simform=sform)

@qpra.route("/qpra/newmodel", methods = ['POST'])
def newModel():  
  mform = ModelForm()# user id를 매개변수로 전달하여 쿼리하여 모델과 시뮬레이션 정보 장전
  if mform.validate_on_submit() or request.method == 'POST':  
    modelname= mform.ModelName.data
    category = mform.Category.data    
    
    frqdist  = mform.FrqDist.data
    param10  = mform.Parameter10.data
    if DIST[frqdist][1]==2:
      param20  = mform.Parameter20.data
    else:
      param20  = None
    
    sDist    = mform.SvrDist.data
    param11  = mform.Parameter11.data
    if DIST[sDist][1]==2:
      param21  = mform.Parameter21.data
    elif DIST[sDist][1]==3:   
      param21  = mform.Parameter21.data
      param31  = mform.Parameter31.data 
    else:
      param21  = None
      param31  = None 

    model = Model(modelname=modelname,category=category,fdist=frqdist,param10=param10,param20=param20,sdist=sDist,param11=param11,param21=param21,param31=param31,user_id=0)
    db.session.add(model)
    db.session.commit()
    flash('새 모델({0})이 추가되었습니다'.format(modelname), 'success')    
  return redirect(url_for('qpra.home'))

@qpra.route("/qpra/<int:id>/updatemodel", methods = ['POST', 'GET'])
def updateModel(id):  
  mform = ModelForm()# user id를 매개변수로 전달하여 쿼리하여 모델과 시뮬레이션 정보 장전  
  if mform.validate_on_submit() or request.method == 'POST':  
    modelname= mform.ModelName.data
    category = mform.Category.data    
    frqdist  = mform.FrqDist.data
    param10  = mform.Parameter10.data
    param20  = None
    if DIST[frqdist][1]==2:
      param20  = mform.Parameter20.data
    else:
      param20  = None
    
    sDist    = mform.SvrDist.data
    param11  = mform.Parameter11.data
    param21  = None
    param31  = None
    if DIST[sDist][1]==2:
      param21  = mform.Parameter21.data
    elif DIST[sDist][1]==3:   
      param21  = mform.Parameter21.data
      param31  = mform.Parameter31.data 
    else:
      param21  = None
      param31  = None  

    model = db.session.query(Model).filter(Model.id==id).update({
      'modelname':modelname,'category':category,'fdist':frqdist,'param10':param10,'param20':param20,'sdist':sDist,'param11':param11,'param21':param21,'param31':param31
    })    
    db.session.commit()
    flash('모델 {0}이 업데이트되었습니다'.format(modelname), 'success')    
    return redirect(url_for('qpra.home'))
  else:    
    sql = sqModelID.format(id)  
    varValues = db.session.execute(sql)
    varValue = [var for var in varValues]
    _,mform.ModelName.data,mform.Category.data,mform.FrqDist.data,mform.Parameter10.data,mform.Parameter20.data,mform.SvrDist.data,mform.Parameter11.data,mform.Parameter21.data,mform.Parameter31.data = varValue[0]
    mform.submit.label.text = 'Update'
    return render_template('update_model.html',id=id,modelform=mform)

@qpra.route("/qpra/<int:id>/delmodel", methods = ['POST','GET'])
def delModel(id):  
  # model = Model.query.get_or_404(id)
  # db.session.delete(model)
  sql = sqDelModel.format(id)
  db.session.execute(sql)
  db.session.commit()
  flash('해당 모델이 삭제되었습니다', 'success')
  return redirect(url_for('qpra.home'))

@qpra.route("/qpra/runsim", methods = ['POST'])
def runSim():
  mform = ModelForm() # user id를 매개변수로 전달하여 쿼리하여 모델과 시뮬레이션 정보 장전
  sform = SimForm()
  if sform.validate_on_submit() or request.method == 'POST':  
    samples = sform.Samples.data
    iter    = sform.Iterations.data
    minimum = sform.Minimum.data
    maximum = sform.Maximum.data
    mean    = sform.Mean.data
    median  = sform.Median.data
    mode    = sform.Mode.data
    stdev   = sform.Standard_Deviation.data
    skew    = sform.Skewness.data
    kurt    = sform.Kurtosis.data
    pct1    = sform.Percentile1.data
    pct2    = sform.Percentile2.data
    tar1    = sform.Target1.data
    tar2    = sform.Target2.data
    bins    = sform.Bins.data
    print(samples,iter,minimum,maximum,mean,median,mode,stdev,skew,kurt,pct1,pct2,tar1,tar2,bins)
  return render_template('qpra.html', modelform=mform,simform=sform)

ESG/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from ESG import db, bcrypt
from ESG.models import User, Post
from ESG.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm)
from ESG.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)

@users.route("/register", methods=['GET', 'POST'])
def register():
  if current_user.is_authenticated:
    return redirect(url_for('main.home'))
  form = RegistrationForm()
  if form.validate_on_submit():
    hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
    user = User(username=form.username.data, email=form.email.data, password=hashed_password)
    db.session.add(user)
    db.session.commit()
    flash('Your account has been created! You are now able to log in', 'success')
    return redirect(url_for('users.login'))
  return render_template('register.html', title='Register', form=form)

@users.route("/login", methods=['GET', 'POST'])
def login():
  if current_user.is_authenticated:
    return redirect(url_for('main.home'))
  form = LoginForm()
  if form.validate_on_submit():
    user = User.query.filter_by(email=form.email.data).first()
    if user and bcrypt.check_password_hash(user.password, form.password.data):
      login_user(user, remember=form.remember.data)
      next_page = request.args.get('next')
      return redirect(next_page) if next_page else redirect(url_for('main.home'))
    else:
      flash('Login Unsuccessful. Please check email and password', 'danger')
  return render_template('login.html', title='Login', form=form)

@users.route("/logout")
def logout():
  logout_user()
  return redirect(url_for('main.home'))

@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
  form = UpdateAccountForm()
  if form.validate_on_submit():
    if form.picture.data:
      picture_file = save_picture(form.picture.data)
      current_user.image_file = picture_file
    current_user.username = form.username.data
    current_user.email = form.email.data
    db.session.commit()
    flash('Your account has been updated!', 'success')
    return redirect(url_for('users.account'))
  elif request.method == 'GET':
    form.username.data = current_user.username
    form.email.data = current_user.email
  image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
  return render_template('account.html', title='Account', image_file=image_file, form=form)

@users.route("/user/<string:username>")
def user_posts(username):
  page = request.args.get('page', 1, type=int)
  user = User.query.filter_by(username=username).first_or_404()
  posts = Post.query.filter_by(author=user)\
    .order_by(Post.date_posted.desc())\
    .paginate(page=page, per_page=5)
  return render_template('user_posts.html', posts=posts, user=user)

@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
  if current_user.is_authenticated:
    return redirect(url_for('main.home'))
  form = RequestResetForm()
  if form.validate_on_submit():
    user = User.query.filter_by(email=form.email.data).first()
    send_reset_email(user)
    flash('An email has been sent with instructions to reset your password.', 'info')
    return redirect(url_for('users.login'))
  return render_template('reset_request.html', title='Reset Password', form=form)

@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
  if current_user.is_authenticated:
    return redirect(url_for('main.home'))
  user = User.verify_reset_token(token)
  if user is None:
    flash('That is an invalid or expired token', 'warning')
    return redirect(url_for('users.reset_request'))
  form = ResetPasswordForm()
  if form.validate_on_submit():
    hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
    user.password = hashed_password
    db.session.commit()
    flash('Your password has been updated! You are now able to log in', 'success')
    return redirect(url_for('users.login'))
  return render_template('reset_token.html', title='Reset Password', form=form)

ESG/templates/create_post.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{{ legend }}</legend>
            <div class="form-group">
                {{ form.title.label(class="form-control-label") }}
                {% if form.title.errors %}
                    {{ form.title(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.title.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.title(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            
            <div class="form-group">
                {{ form.file.label(class="form-control-label") }} 
                
                <!-- [<a href="{{ url_for('posts.upload') }}">Select File</a>] -->
                <form action="{{ url_for('posts.upload') }}" method = "POST" enctype = "multipart/form-data">
                <input type = 'file' name = 'file' />
                <input type = 'submit'/>
                </form>                    
                {% if form.file.errors %}
                    {{ form.file(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.file.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.file(class="form-control form-control-lg") }}                    
                {% endif %}
            </div>

            <div class="form-group">
                {{ form.content.label(class="form-control-label") }} 
                {% if form.content.errors %}
                    {{ form.content(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.content.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.content(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
{% endblock content %}

ESG/templates/home.html
{% extends "layout.html" %}
{% block content %}
  {% for post in posts.items %}
    <article class="media content-section">
      <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
      <div class="media-body">
        <div class="article-metadata">
          <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
          <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
        </div>
        <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
        <p class="article-content">{{ post.content }}</p>
      </div>
    </article>
  {% endfor %}
  {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
    {% if page_num %}
      {% if posts.page == page_num %}
        <a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
      {% else %}
        <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
      {% endif %}
    {% else %}
      ...
    {% endif %}
  {% endfor %}
{% endblock content %}

ESG/templates/layout.html
<!DOCTYPE html>
<html>
<head>  
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css"/>
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
  
  {% if title %}
    <title>HertzAlpha ESG - {{ title }}</title>
  {% else %}
    <title>HertzAlpha ESG  </title>
  {% endif %}
</head>
<body>
  <header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
      <div class="container">
        <a class="navbar-brand mr-4" href="/"><img src="{{ url_for('static', filename='/img/hertzalpha.png') }}" height="50"/></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarToggle">
          <div class="navbar-nav mr-auto">
            <a class="nav-item nav-link" href="{{ url_for('qpra.home') }}">QUANTITATIVE PROJECT RISK</a>
          </div>
          <!-- Navbar Right Side -->
          <div class="navbar-nav">
            {% if current_user.is_authenticated %}
            <a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}">New Post</a>
            <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
            <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
            {% else %}
            <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
            <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
            {% endif %}
            <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
          </div>
        </div>
      </div>
    </nav>
  </header>
  <main role="main" class="container">
    <div class="row">
      <div class="col-md-8">
        {% with messages = get_flashed_messages(with_categories=true) %}
          {% if messages %}
            {% for category, message in messages %}
              <div class="alert alert-{{ category }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
        {% endwith %}
        {% block content %}{% endblock %}
      </div>
      <div class="col-md-4">
        <div class="content-section">
          <h3>Sidebar</h3>
          <p class='text-muted'>Your information
            <ul class="list-group">
              <li class="list-group-item list-group-item-light"><i class="fas fa-user-cog"></i> Profile</li>
              <li class="list-group-item list-group-item-light"><i class="fas fa-concierge-bell"></i> Services</li>
              <li class="list-group-item list-group-item-light"><i class="fas fa-question-circle"></i> Help</li>
            </ul>
          </p>
        </div>
      </div>
    </div>
  </main>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

<!-- Modal -->
{% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    {% for category, message in messages %}
      <div class="modal fade" id="msgModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
          {% if category=='create' %}
            <div class="modal-header">
              <h5 class="modal-title" id="priModal">HertzAlpha</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <span class="alert-inner--icon"><i class="fas fa-plus-circle"></i></span>
              <span class="alert-inner--text">{{ message|safe }}</span>
            </div>    
          {% elif category=='update' %}
            <div class="modal-header">
              <h5 class="modal-title" id="secModal">HertzAlpha</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <span class="alert-inner--icon"><i class="fas fa-check-circle"></i></span>
              <span class="alert-inner--text">{{ message|safe }}</span>
            </div>
          {% elif category=='delete' %}
            <div class="modal-header">
              <h5 class="modal-title" id="donModal">HertzAlpha</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <span class="alert-inner--icon"><i class="fas fa-minus-circle"></i></span>
              <span class="alert-inner--text">{{ message|safe }}</span>
            </div>
          {% elif category=='info' %}
            <div class="modal-header">
              <h5 class="modal-title" id="hupModal">HertzAlpha</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <span class="alert-inner--icon"><i class="far fa-bell"></i></span>
              <span class="alert-inner--text">{{ message|safe }}</span>
            </div>
          {% elif category=='warning' %}
            <div class="modal-header">
              <h5 class="modal-title" id="wrnModal">HertzAlpha</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <span class="alert-inner--icon"><i class="fas fa-exclamation-circle"></i></span>
              <span class="alert-inner--text">{{ message|safe }}</span>
            </div>
          {% elif category=='danger' %}
            <div class="modal-header">
              <h5 class="modal-title" id="snpModal">HertzAlpha</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <span class="alert-inner--icon"><i class="fas fa-fire"></i></span>
              <span class="alert-inner--text">{{ message|safe }}</span>
            </div>
          {% else %}
            <div class="modal-header">
              <h5 class="modal-title">HertzAlpha</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <span class="alert-inner--icon"><i class="fas fa-fire"></i></span>
              <span class="alert-inner--text">{{ message|safe }}</span>
            </div>
          {% endif %}
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">닫기</button>
            </div>
          </div>
        </div>
      </div>
    {% endfor %}
    <script type="text/javascript">
      $(document).ready(function(){ $("#msgModal").modal('show'); });
    </script>
  {% endif %}
{% endwith %}
</body>
</html>

ESG/templates/post.html
{% extends "layout.html" %}
{% block content %}
  <article class="media content-section">
    <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
        <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
        {% if post.author == current_user %}
          <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
            <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
          </div>
        {% endif %}
      </div>
      <h2 class="article-title">{{ post.title }}</h2>
      <p class="article-content">{{ post.content }}</p>
      
    </div>
  </article>
  <!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

ESG/templates/upload.html
{% extends 'layout.html' %}
{% block title %}File Upload{% endblock %}
{% block content %}
{%with messages = get_flashed_messages()%}
{%if messages %}
  <script type="text/javascript">
    alert("{{messages[-1]}}");
  </script>
  {%endif%}
{%endwith%}
<form action="{{ url_for('upload') }}" method = "POST" enctype = "multipart/form-data">
<input type = 'file' name = 'file' />
<input type = 'submit'/>
</form>
{% endblock %}